package com.sample
 
import com.sample.MediclaimProcessModel;

rule "Check_User_Age_in"
	
	when
		$m : MediclaimProcessModel( userAge > 30  )
	then
		System.out.println("Your age is more than 30");
		$m.setResult(true);
end

rule "Check_User_Age_out"
	
	when
		$m : MediclaimProcessModel( userAge < 30  )
	then
		System.out.println("Your age is less than 30");
		$m.setResult(true);
end


rule "Check_User_Coverage_Status_in"
	
	when
		$m:MediclaimProcessModel(userCoverage == true)
	then
	   	System.out.println("You are covered under this medical insurnace");
		$m.setResult(true);
end

rule "Check_User_Coverage_Status_out"
	
	when
		$m:MediclaimProcessModel(userCoverage == false)
	then
	   	System.out.println("You are not covered under this medical insurnace");
		$m.setResult(true);
end
