package com.sample

import com.sample.HelloProcessModel;

rule "Bangaloreuser_Rule"
	
	no-loop true
	ruleflow-group "EvalLoopcondition"
	when
		m:HelloProcessModel(userlocation in ("Bangalore"), count < 4)
	then
		m.setLoopcondition(10);update(m);
end


rule "MysoreUser_Rule"
	
	no-loop true
	ruleflow-group "EvalLoopcondition"
	when
		m:HelloProcessModel(userlocation in ("Mysore"), count < 3)
	then
		m.setLoopcondition(5);update(m);
end


rule "DelhiUser_Rule"
	
	no-loop true
	ruleflow-group "EvalLoopcondition"
	when
		m:HelloProcessModel(userlocation in ("Delhi"), count < 6)
	then
		m.setLoopcondition(8);update(m);
end
